### ISSUE TITLE
OSX binary not working

### ISSUE THREAD

**Issue by ayan4m1** [ysmood/use-node#3]
I have a directory with a package.json specifying:

```json
"engines": {
  "node": "18.x"
}
```

I have used the "manual binary approval" process in #2 but when I run use-node I get

```
git:(main) use-node

panic: improper constraint: <nil>

goroutine 1 [running]:

[github.com/ysmood/use-node/pkg/utils.E(..](http://github.com/ysmood/use-node/pkg/utils.E(..).)

/Users/yad/repos/use-node/pkg/utils/utils.go:5

[github.com/ysmood/use-node/pkg/node.getNodeInfo({0x0](http://github.com/ysmood/use-node/pkg/node.getNodeInfo(%7B0x0)?, 0x20?})

/Users/yad/repos/use-node/pkg/node/node.go:127 +0x2f4

[github.com/ysmood/use-node/pkg/node.GetNodePath({0x13847b8](http://github.com/ysmood/use-node/pkg/node.GetNodePath(%7B0x13847b8)?,
0xc00001c090}, {0x0, 0x0}, {0x1382340?, 0xc00011c280})

/Users/yad/repos/use-node/pkg/node/node.go:22 +0xa5

main.main()

/Users/yad/repos/use-node/main.go:67 +0x26c
```

**Comment by ysmood** [comment]
Please try the latest version and it help you to fix the issue, it has better error message:

https://github.com/ysmood/use-node/releases/tag/v0.2.3
